version: "3.5"

services:
  namenode:
    image: otosky/hadoop-namenode:2.10.0
    container_name: namenode
    ports:
      - 50070:50070
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    networks:
      - hadoop

  datanode:
    image: otosky/hadoop-datanode:2.10.0
    container_name: datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop
  
  resourcemanager:
    image: otosky/hadoop-resourcemanager:2.10.0
    container_name: resourcemanager
    ports:
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop

  nodemanager:
    image: otosky/hadoop-nodemanager:2.10.0
    container_name: nodemanager
    ports:
      - 8042:8042
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop
  
  historyserver:
    image: otosky/hadoop-historyserver:2.10.0
    container_name: historyserver
    ports:
      - 8188:8188
      - 19888:19888
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    networks:
      - hadoop

  hive-server:
    image: otosky/hadoop-hive:2.10.0
    container_name: hive-server
    env_file:
      - ./hadoop.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
      - "10002:10002"
    networks:
      - hadoop

  hive-metastore:
    image: otosky/hadoop-hive:2.10.0
    container_name: hive-metastore
    env_file:
      - ./hadoop.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    networks:
      - hadoop

  hive-metastore-postgresql:
    image: otosky/hive-postgres-metastore:11.7
    container_name: hive-metastore-postgresql
    environment: 
      POSTGRES_USER: bot
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hiveuser"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - hadoop

  client:
    image: otosky/hadoop-client:2.10.0
    container_name: hadoop-client
    env_file:
      - ./hadoop.env
    ports:
      - "4040:4040"
      - "8081:8081"
      - "5432:5432"
    environment:
      SERVICE_PRECONDITION: "historyserver:8188 hive-server:10000"
    networks:
      - hadoop

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:

networks:
  hadoop:
    name: hadoop